import React from 'react'
import Head from "next/head"
import Navbar from '../components/Navbar'
import ContactHero from '../components/ContactHero'
import Footer from './../components/Footer';
import Looking from '../components/Looking';


const contact = () => {
  return (
    <div>
        <Head>
         <title>Mpha projects</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
  
    <Navbar/>
   
      
      <ContactHero/>
      <Looking/>
      <Footer/>
    </div>
  )
}

export default contact