import Head from 'next/head'
import Navbar from '../components/Navbar'
import Hero from '../components/Hero'
import Aboutmore from '../components/Aboutmore';


export default function Home() {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <Navbar/>
    <Hero/>
    <Aboutmore/>
    </div>
  )
}
