import React from "react";
import Hero from "../components/Hero";
import Navbar from "../components/Navbar";
import Head from "next/head";
import More from "../components/More";
import Looking from "../components/Looking";
import Footer from "../components/Footer";

const services = () => {
  return (
    <div className="w-[full] relative">
      <Head>
        <title>Mpha projects</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      
      <Hero />
      
     
     <div className="grid grid-col-1 bg-white z-16 md:grid-cols-2 gap-1 pt-3 md:py-[4rem] item-center mx-auto">
        <div className="px-2 md:px-[3rem]">
          <h1 className="text-Poppins text-xl md:text-3xl font-bold font-Poppins pl-3 pt-2">
            About Us
          </h1>
          <p className="text-[15px] font-Poppins font-semibold opacity-70 pt-5">
          Mpha Projects is a well-established and empowered company that
            contributes a wealth of experience to the construction industry. We
            are a specialist project management construction company, working in
            the supply and installation of Structural, Mechanical, Piping,
            Platework, Electrical & Instrumentation Fields.
            <br /> <br />
            The active participation of Senior Management, who have a personal
            stake in the company, ensure that your project receives the best
            attention at all times. This unyielding dedication to the successful
            execution of your project ensures that your safety, quality, time
            and cost goals are achieved.
            <br />
            <br /> Our well established network of suppliers, sub-contractors
            and our project management controls, ensures that our time delivery
            commitments are kept for projects of all magnitude. Our large fleet
            of mobile cranes, in excess of 50, and core competent teams ensure
            that your project is executed on time and to your satisfaction.
            <br /> <br /> Our continued safety record is a source of pride,
            which demonstrates our commitment and dedication to ensuring a safe
            working environment for all our employees.
          </p>
        </div>
        <div className="px-2 md:px-[3rem] bg-white z-16">
          <h1 className="text-Poppins md:underline md:underline-offset-[1rem] text-xl md:text-3xl font-bold font-Poppins pl-3 pt-2">
            Transforming Our People & Society
          </h1>
          <p className="text-[15px] font-Poppins font-semibold opacity-70 pt-5">
          Mpha Projects is socially and economically aware of the
            inequalities that may exist in our company and in South Africa as a
            whole and we are fully committed to re address these needs.<br/><br/> We view
            BEE as an integral part of South Africa’s growth and development
            plan and believe BEE must be implemented in a coordinated and
            integrated manner as recommended by the Black Economic Empowerment
            Commission.<br/> <br/>As one step towards BEE empowerment, we have concluded a
            deal to transfer 26.06% Black Ownership to KDI Mining and Investec.
            It is our intention to continue supporting and developing existing
            and new BEE initiatives.<br/> <br/>We recognise that our Human Resources are
            our greatest asset. To this end, a comprehensive training program is
            in place to enhance skills, and develop talent. We encourage our
            employees to embark on a journey of self-improvement and skills
            development.
          </p>
        </div>
      </div>
      <More/>
      <Looking/>
      <Footer/>
    </div>
  );
};

export default services;
